"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import styles from "./wizard.module.css";

type State = { status: string; currentStep: string; interestsStatus: string; recommendationsStatus: string };
type Consents = { currentTermsVersion: string; currentPrivacyVersion: string };
type Tag = { id: string; namePl: string; nameEn: string; category: string };
type Place = { placeId: number; displayName: string };
type Recommendations = {
  profiles: { profileId: string; handle: string; displayName: string; distanceBand?: string }[];
  communities: { communityId: string; name: string; memberCount: number; distanceBand?: string }[];
  emptyReason?: string;
};

const copy = {
  pl: { title: "Stwórz swoją przestrzeń", subtitle: "Możesz wrócić do każdego kroku. Udostępniasz tylko to, co wybierzesz.", waiting: "Przygotowujemy Twoje konto…", consent: "18+ i zasady", adult: "Potwierdzam, że mam co najmniej 18 lat", accept: "Akceptuję aktualny regulamin i politykę prywatności", profile: "Twój profil", handle: "Handle", display: "Nazwa wyświetlana", bio: "Bio (opcjonalne)", avatar: "Avatar (opcjonalny)", location: "Miasto lub region (opcjonalne)", search: "Szukaj", interests: "Zainteresowania", suggestions: "Polecane dla Ciebie", visibility: "Widoczność", public: "Publiczny dla zalogowanych", private: "Prywatny — pełne dane dla zaakceptowanych obserwujących", next: "Dalej", skip: "Pomiń", finish: "Zakończ onboarding", join: "Dołącz", follow: "Obserwuj", noSuggestions: "Dodaj lokalizację lub kinktag, aby otrzymać rekomendacje.", error: "Nie udało się zapisać. Spróbuj ponownie." },
  en: { title: "Create your space", subtitle: "You can return to every step. You only share what you choose.", waiting: "Preparing your account…", consent: "18+ and policies", adult: "I confirm that I am at least 18", accept: "I accept the current terms and privacy policy", profile: "Your profile", handle: "Handle", display: "Display name", bio: "Bio (optional)", avatar: "Avatar (optional)", location: "City or region (optional)", search: "Search", interests: "Interests", suggestions: "Recommended for you", visibility: "Visibility", public: "Public to signed-in members", private: "Private — full details for approved followers", next: "Continue", skip: "Skip", finish: "Finish onboarding", join: "Join", follow: "Follow", noSuggestions: "Add a location or kinktag to receive recommendations.", error: "Could not save. Please try again." },
};

export function OnboardingWizard({ lang }: { lang: "pl" | "en" }) {
  const t = copy[lang]; const router = useRouter();
  const [state, setState] = useState<State | null>(null); const [consents, setConsents] = useState<Consents | null>(null);
  const [tags, setTags] = useState<Tag[]>([]); const [selectedTags, setSelectedTags] = useState<string[]>([]);
  const [places, setPlaces] = useState<Place[]>([]); const [placeQuery, setPlaceQuery] = useState(""); const [selectedPlace, setSelectedPlace] = useState<number | null>(null);
  const [recommendations, setRecommendations] = useState<Recommendations | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);

  const load = useCallback(async () => {
    const [stateResponse, consentsResponse, tagsResponse] = await Promise.all([api("onboarding"), api("accounts/me/consents"), api("tags")]);
    if (stateResponse.status === 409) { setState({ status: "Waiting", currentStep: "account", interestsStatus: "Pending", recommendationsStatus: "Pending" }); return; }
    if (stateResponse.ok) setState(await stateResponse.json()); if (consentsResponse.ok) setConsents(await consentsResponse.json()); if (tagsResponse.ok) setTags(await tagsResponse.json());
  }, []);

  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (state?.currentStep !== "account") return; const timer = window.setInterval(() => void load(), 2000); return () => window.clearInterval(timer); }, [state?.currentStep, load]);
  useEffect(() => { if (state?.currentStep === "recommendations") void api("recommendations/onboarding").then(async response => { if (response.ok) setRecommendations(await response.json()); }); }, [state?.currentStep]);

  async function submit(action: () => Promise<Response>) { setBusy(true); setError(""); try { const response = await action(); if (!response.ok) throw new Error(); await load(); } catch { setError(t.error); } finally { setBusy(false); } }
  if (!state || state.currentStep === "account") return <Shell t={t}><p className={styles.waiting}>{t.waiting}</p></Shell>;
  if (state.currentStep === "done") { router.replace(`/${lang}`); return null; }

  return <Shell t={t}>
    <Progress current={state.currentStep} />
    {error ? <p className={styles.error}>{error}</p> : null}
    {state.currentStep === "consents" && consents ? <ConsentStep t={t} busy={busy} onSubmit={(adult, accepted) => submit(() => api("onboarding/consents", { method: "PUT", body: { adultConfirmed: adult && accepted, termsVersion: consents.currentTermsVersion, privacyVersion: consents.currentPrivacyVersion, locale: lang } }))} /> : null}
    {state.currentStep === "profile" ? <ProfileStep t={t} busy={busy} places={places} selectedPlace={selectedPlace} placeQuery={placeQuery} setPlaceQuery={setPlaceQuery} choosePlace={setSelectedPlace} searchPlaces={async () => { const response = await api(`locations/places?query=${encodeURIComponent(placeQuery)}`); if (response.ok) setPlaces(await response.json()); }} onSubmit={(form: Record<string, FormDataEntryValue | null>, avatar: File | null) => submit(async () => { let avatarAssetId: string | null = null; if (avatar) avatarAssetId = await uploadAvatar(avatar); const response = await api("profiles/me", { method: "POST", body: { ...form, avatarAssetId } }); if (response.ok && selectedPlace) await api("locations/me", { method: "PUT", body: { placeId: selectedPlace } }); return response; })} /> : null}
    {state.currentStep === "interests" ? <InterestsStep t={t} tags={tags} selected={selectedTags} setSelected={setSelectedTags} busy={busy} next={() => submit(async () => { const response = await api("tags/me", { method: "PUT", body: { tagIds: selectedTags } }); if (response.ok) await api("onboarding/steps/interests/complete", { method: "POST" }); return response; })} skip={() => submit(() => api("onboarding/steps/interests/skip", { method: "POST" }))} /> : null}
    {state.currentStep === "recommendations" ? <RecommendationsStep t={t} data={recommendations} busy={busy} join={(id: string) => api(`communities/${id}/memberships/me`, { method: "POST" })} follow={(id: string) => api(`social-graph/follows/${id}`, { method: "PUT" })} next={() => submit(() => api("onboarding/steps/recommendations/complete", { method: "POST" }))} skip={() => submit(() => api("onboarding/steps/recommendations/skip", { method: "POST" }))} /> : null}
    {state.currentStep === "visibility" || state.currentStep === "complete" ? <VisibilityStep t={t} busy={busy} onSubmit={(visibility: string) => submit(async () => { const response = await api("profiles/me/visibility", { method: "PUT", body: { visibility } }); if (response.ok) { const complete = await api("onboarding/complete", { method: "POST" }); if (complete.ok) router.replace(`/${lang}`); return complete; } return response; })} /> : null}
  </Shell>;
}

function Shell({ t, children }: { t: typeof copy.pl; children: React.ReactNode }) { return <main className={styles.shell}><section className={styles.card}><a href={`/${t === copy.pl ? "pl" : "en"}`} className={styles.brand}>kinxter</a><header><h1>{t.title}</h1><p>{t.subtitle}</p></header>{children}</section></main>; }
function Progress({ current }: { current: string }) { const steps = ["consents", "profile", "interests", "recommendations", "visibility"]; const active = Math.max(0, steps.indexOf(current)); return <div className={styles.progress} aria-label="Onboarding progress">{steps.map((step, index) => <span key={step} className={index <= active ? styles.active : ""}>{index + 1}</span>)}</div>; }
function ConsentStep({ t, busy, onSubmit }: { t: typeof copy.pl; busy: boolean; onSubmit: (adult: boolean, accepted: boolean) => void }) { const [adult, setAdult] = useState(false); const [accepted, setAccepted] = useState(false); return <form onSubmit={event => { event.preventDefault(); onSubmit(adult, accepted); }}><h2>{t.consent}</h2><label className={styles.check}><input type="checkbox" checked={adult} onChange={e => setAdult(e.target.checked)} />{t.adult}</label><label className={styles.check}><input type="checkbox" checked={accepted} onChange={e => setAccepted(e.target.checked)} />{t.accept}</label><button disabled={busy || !adult || !accepted}>{t.next}</button></form>; }
function ProfileStep({ t, busy, places, selectedPlace, placeQuery, setPlaceQuery, choosePlace, searchPlaces, onSubmit }: any) { const [avatar, setAvatar] = useState<File | null>(null); return <form onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); onSubmit({ handle: data.get("handle"), displayName: data.get("displayName"), bio: data.get("bio") || null }, avatar); }}><h2>{t.profile}</h2><label>{t.handle}<input name="handle" minLength={3} maxLength={32} pattern="[A-Za-z0-9._]+" required /></label><label>{t.display}<input name="displayName" maxLength={120} required /></label><label>{t.bio}<textarea name="bio" maxLength={500} /></label><label>{t.avatar}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event => setAvatar(event.target.files?.[0] ?? null)} /></label><label>{t.location}<div className={styles.inline}><input value={placeQuery} onChange={e => setPlaceQuery(e.target.value)} /><button type="button" onClick={searchPlaces}>{t.search}</button></div></label>{places.length ? <div className={styles.options}>{places.map((place: Place) => <button className={selectedPlace === place.placeId ? styles.selected : ""} type="button" key={place.placeId} onClick={() => choosePlace(place.placeId)}>{place.displayName}</button>)}</div> : null}<button disabled={busy}>{t.next}</button></form>; }
function InterestsStep({ t, tags, selected, setSelected, busy, next, skip }: any) { return <section><h2>{t.interests}</h2><div className={styles.tags}>{tags.map((tag: Tag) => { const checked = selected.includes(tag.id); return <label key={tag.id} className={checked ? styles.tagSelected : ""}><input type="checkbox" checked={checked} onChange={() => setSelected(checked ? selected.filter((id: string) => id !== tag.id) : [...selected, tag.id])} />{t === copy.pl ? tag.namePl : tag.nameEn}</label>; })}</div><Actions t={t} busy={busy} next={next} skip={skip} /></section>; }
function RecommendationsStep({ t, data, busy, join, follow, next, skip }: any) { return <section><h2>{t.suggestions}</h2>{!data || (!data.profiles.length && !data.communities.length) ? <p>{data?.emptyReason ?? t.noSuggestions}</p> : <div className={styles.recommendations}>{data.communities.map((item: any) => <article key={item.communityId}><strong>{item.name}</strong><small>{item.memberCount} members · {item.distanceBand ?? ""}</small><button type="button" onClick={() => void join(item.communityId)}>{t.join}</button></article>)}{data.profiles.map((item: any) => <article key={item.profileId}><strong>{item.displayName}</strong><small>@{item.handle} · {item.distanceBand ?? ""}</small><button type="button" onClick={() => void follow(item.profileId)}>{t.follow}</button></article>)}</div>}<Actions t={t} busy={busy} next={next} skip={skip} /></section>; }
function VisibilityStep({ t, busy, onSubmit }: any) { const [visibility, setVisibility] = useState(""); return <section><h2>{t.visibility}</h2><label className={styles.choice}><input type="radio" name="visibility" value="Public" onChange={e => setVisibility(e.target.value)} />{t.public}</label><label className={styles.choice}><input type="radio" name="visibility" value="Private" onChange={e => setVisibility(e.target.value)} />{t.private}</label><button disabled={busy || !visibility} onClick={() => onSubmit(visibility)}>{t.finish}</button></section>; }
function Actions({ t, busy, next, skip }: any) { return <div className={styles.actions}><button type="button" className={styles.secondary} disabled={busy} onClick={skip}>{t.skip}</button><button type="button" disabled={busy} onClick={next}>{t.next}</button></div>; }
async function uploadAvatar(file: File) { const create = await api("media/avatar-uploads", { method: "POST", body: { contentType: file.type, size: file.size } }); if (!create.ok) throw new Error(); const upload = await create.json(); const put = await fetch(upload.uploadUrl, { method: "PUT", headers: { "content-type": file.type }, body: file }); if (!put.ok) throw new Error(); const complete = await api(`media/avatar-uploads/${upload.assetId}/complete`, { method: "POST" }); if (!complete.ok) throw new Error(); return upload.assetId as string; }
function api(path: string, init: { method?: string; body?: unknown } = {}) { return fetch(`/api/kinxter/${path}`, { method: init.method ?? "GET", cache: "no-store", headers: init.body !== undefined ? { "content-type": "application/json" } : undefined, body: init.body !== undefined ? JSON.stringify(init.body) : undefined }); }
