"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import styles from "../admin.module.css";

type Tag = { id: string; slug: string; category: string; namePl: string; nameEn: string; descriptionPl?: string; descriptionEn?: string; sortOrder: number; isActive: boolean };
export default function TagsPage() {
  const [tags, setTags] = useState<Tag[]>([]); const [error, setError] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/kinxter/admin/tags", { cache: "no-store" }); if (response.ok) setTags(await response.json()); else setError(`HTTP ${response.status}`); }, []);
  useEffect(() => { void load(); }, [load]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const response = await fetch("/api/kinxter/admin/tags", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ slug: data.get("slug"), category: data.get("category"), namePl: data.get("namePl"), nameEn: data.get("nameEn"), descriptionPl: null, descriptionEn: null, sortOrder: Number(data.get("sortOrder")) || 0 }) }); if (response.ok) { event.currentTarget.reset(); await load(); } else setError(`HTTP ${response.status}`); }
  async function toggle(tag: Tag) { await fetch(`/api/kinxter/admin/tags/${tag.id}`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ category: tag.category, namePl: tag.namePl, nameEn: tag.nameEn, descriptionPl: tag.descriptionPl, descriptionEn: tag.descriptionEn, sortOrder: tag.sortOrder, isActive: !tag.isActive }) }); await load(); }
  return <AdminShell title="Kinktagi"><section className={styles.panel}><div className={styles.panelHeader}><h2>Nowy kinktag</h2></div><form onSubmit={create} style={{ display: "grid", gridTemplateColumns: "repeat(5,minmax(120px,1fr))", gap: 10, padding: 16 }}><input name="slug" placeholder="slug" required /><input name="category" placeholder="kategoria" required /><input name="namePl" placeholder="nazwa PL" required /><input name="nameEn" placeholder="nazwa EN" required /><input name="sortOrder" type="number" placeholder="kolejność" /><button>Dodaj</button></form></section>{error ? <p>{error}</p> : null}<section className={styles.panel}><div className={styles.table} role="table">{tags.map(tag => <div className={styles.tableRow} role="row" key={tag.id} style={{ gridTemplateColumns: "1fr 1fr 1fr 100px" }}><span><strong>{tag.namePl}</strong><br /><small>{tag.slug}</small></span><span>{tag.category}</span><span>{tag.isActive ? "Aktywny" : "Nieaktywny"}</span><button onClick={() => void toggle(tag)}>{tag.isActive ? "Wyłącz" : "Włącz"}</button></div>)}</div></section></AdminShell>;
}
function AdminShell({ title, children }: { title: string; children: React.ReactNode }) { return <main className={styles.adminShell}><aside className={styles.sidebar}><div className={styles.brand}><span>K</span><div><strong>Kinxter</strong><small>Admin</small></div></div><nav className={styles.nav}><a className={styles.navItem} href="/">Monitoring</a><a className={`${styles.navItem} ${styles.active}`} href="/tags">Kinktagi</a><a className={styles.navItem} href="/communities">Społeczności</a></nav></aside><section className={styles.content}><header className={styles.topbar}><h1 className={styles.heading}>{title}</h1></header>{children}</section></main>; }
