// <auto-generated />
using System;
using Kinxter.Locations.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kinxter.Locations.Infrastructure.Migrations
{
    [DbContext(typeof(LocationsDbContext))]
    [Migration("20260726152040_InitialLocations")]
    partial class InitialLocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("locations")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kinxter.Locations.Model.EntityLocation", b =>
                {
                    b.Property<string>("EntityType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<long>("PlaceId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EntityType", "EntityId");

                    b.HasIndex("PlaceId");

                    b.ToTable("entity_locations", "locations");
                });

            modelBuilder.Entity("Kinxter.Locations.Model.Place", b =>
                {
                    b.Property<long>("GeoNameId")
                        .HasColumnType("bigint");

                    b.Property<string>("AdminRegion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("GeoNameId");

                    b.HasIndex("Name");

                    b.HasIndex("CountryCode", "AdminRegion", "Name");

                    b.ToTable("places", "locations");
                });

            modelBuilder.Entity("Kinxter.Locations.Model.EntityLocation", b =>
                {
                    b.HasOne("Kinxter.Locations.Model.Place", null)
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
