// <auto-generated />
using System;
using Kinxter.SocialGraph.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kinxter.SocialGraph.Infrastructure.Migrations
{
    [DbContext(typeof(SocialGraphDbContext))]
    [Migration("20260726152044_InitialSocialGraph")]
    partial class InitialSocialGraph
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("social_graph")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kinxter.SocialGraph.Model.Follow", b =>
                {
                    b.Property<Guid>("FollowerProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowedProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FollowerProfileId", "FollowedProfileId");

                    b.HasIndex("FollowedProfileId", "Status");

                    b.ToTable("follows", "social_graph");
                });
#pragma warning restore 612, 618
        }
    }
}
